return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "regex",
      "tsx",
      "typescript",
      "yaml",
      "astro",
      "css",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitignore",
      "go",
      "helm",
      "graphql",
      "htmldjango",
      "jsdoc",
      "jsonnet",
      "luadoc",
      "nix",
      "ssh_config",
      "templ",
    },
  },
}
